### ISSUE TITLE
使用Docker创建后查看日志发现数据库无法访问

### ISSUE THREAD

**Issue by Hopeless** [taomujian/linbing#10]
作者您好，clone下来的内容中dockerfile文件中默认的数据库密码为1234567，mysql.py中保存的密码为123456，在创建镜像时已经将密码同一改为123456。
以下是遇到的问题：
创建镜像并运行后，可以正常注册并登录，但是添加目标后一直是扫描目录状态，访问docker中的uwsgi日志，发现以下内容：

> *** Operational MODE: preforking+threaded ***
added /root/flask/ to pythonpath.
(2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
Traceback (most recent call last):
  File "/root/flask/run.py", line 37, in <module>
    mysqldb.create_database('linbing')
  File "/root/flask/app/mysql.py", line 54, in create_database
    cursor.close()
UnboundLocalError: local variable 'cursor' referenced before assignment
unable to load app 0 (mountpoint='') (callable not found or import error)
(2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
Traceback (most recent call last):
  File "/root/flask/run.py", line 37, in <module>
    mysqldb.create_database('linbing')
  File "/root/flask/app/mysql.py", line 54, in create_database
    cursor.close()
UnboundLocalError: local variable 'cursor' referenced before assignment
unable to load app 0 (mountpoint='') (callable not found or import error)

想请教一下该如何解决，十分感谢~~~

**Comment by taomujian** [comment]
按说能注册和登陆,说明和数据库交互是没有问题的,我试下docker版的,

**Comment by taomujian** [comment]
子域名爆破有问题,这个我到周末再试下,之前没用docker版的试子域名爆破,修复了docker之前的一些错误,你先试用下,之后我再更新我都试下

**Comment by Hopeless** [comment]
额。。更新后build镜像出错。

> Could not import runpy module
Traceback (most recent call last):
  File "/Python-3.8.1/Lib/runpy.py", line 15, in <module>
    import importlib.util
  File "/Python-3.8.1/Lib/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/Python-3.8.1/Lib/contextlib.py", line 4, in <module>
    import _collections_abc
SystemError: <built-in function compile> returned NULL without setting an error
generate-posix-vars failed
make[1]: *** [pybuilddir.txt] Error 1
make[1]: Leaving directory `/Python-3.8.1'
make: *** [profile-opt] Error 2

**Comment by taomujian** [comment]
...好奇怪，我本地编译是通过的，可以用的,出错后编译停止了吗？

**Comment by Hopeless** [comment]
编译停止了，不能生成镜像。

**Comment by taomujian** [comment]
再试试呢，centos太麻烦了，还得自己编译gcc,然后编译安装python3.8,有时间了换成ubuntu的镜像,子域名问题也解决下

**Comment by Hopeless** [comment]
镜像创建成功了，注册出现问题。。
> Traceback (most recent call last):
  File "/root/flask/run.py", line 39, in <module>
    sender = MailSender(config.get('Email', 'email_address'), config.get('Email', 'secret'))
  File "/usr/local/python3.8/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/python3.8/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Email'
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "/root/flask/run.py", line 39, in <module>
    sender = MailSender(config.get('Email', 'email_address'), config.get('Email', 'secret'))
  File "/usr/local/python3.8/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/python3.8/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Email'
unable to load app 0 (mountpoint='') (callable not found or import error)

另外大佬要不您再优化优化，别自己编译gcc了，编译一次三个小时有点吃不消😄
换镜像举双手赞成，直接放到Kali里面用美滋滋。

**Comment by taomujian** [comment]
兄弟，我邮箱taomujian@protonmail.com,你联系下我呢

**Comment by Hopeless** [comment]
给您发邮件了~添麻烦了~

**Comment by taomujian** [comment]
兄弟，我又优化了下，麻烦你在哪试下呢，我在本地试的，2种镜像都可以注册登陆了
